### ISSUE TITLE
Missing doctype in all pages

### ISSUE THREAD

**Issue by fernandoporazzi** [mozilla/charts#28]
I noticed every page is missing the doctype declaration. Could I fix it?

**Comment by klahnakoski** [comment]
That would be greatly appreciated! Please send a pull request to the staging branch (called allizom), or the "dev" branch (which is currently unstable, so not the best place to put a clean patch). 

If you want to contact me, you can find me on IRC as ekyle@mozilla.org.  I am usually in the #ateam channel.

**Comment by fernandoporazzi** [comment]
Well, I've sent a Pull Request, but I send it to the `dev` branch. Is it possible to merge a PR from the `dev` branch to `allizom` branch?

**Comment by klahnakoski** [comment]
yes, the "dev" branch is preferred in general, and will propagate to the other branches eventually.

**Comment by klahnakoski** [comment]
this was completed ages ago.
