### ISSUE TITLE
make it clear that P1 bugs aren't "blockers"

### ISSUE THREAD

**Issue by globau** [mozilla/charts#40]
https://twitter.com/stshank/status/903114714401521665
> Mozilla still must fix 63  priority-1 Quantum Flow bugs by the November 14 release date for @firefox 57. https://charts.mozilla.org/quantum/blockers.html …

this isn't correct, within the context of quantum P1 just means "work on these first".  this should be made clear on the dashboard.

**Comment by klahnakoski** [comment]
fixed with https://github.com/mozilla/charts/pull/41
